---
- hosts: all
  gather_facts: no
  tasks:
    - name: check for apache
      command: rpm -q mod_ssl
      register: modssl
      ignore_errors: true

    - name: ensure openssl is latest
      yum: name=openssl state=latest
      when: modssl|success

    - name: ensure SSLv3 is disabled
      lineinfile:
        dest=/etc/httpd/conf.d/ssl.conf
        regexp=^SSLProtocol
        line="SSLProtocol all -SSLv2 -SSLv3"
        state=present
        backup=yes
      when: modssl|success
      notify: restart apache

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
